### ISSUE TITLE
FontBakery Report -- Check 064 -- WARN: font lacks caret position values

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/staatliches#11]
## Fontbakery report

<details>
<summary><b>[1] Staatliches-Regular.ttf</b></summary>
<details>
<summary>:warning: <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/064](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/064)
* :warning: **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 1 | 0 | 0 | 0 |
| 0% | 0% | 100% | 0% | 0% | 0% |

**Comment by eliheuer** [comment]
I'm looking at this now and I'm not sure what glyphs need caret positions. I added them to everything that might need one and got nothing.

**Comment by davelab6** [comment]
The check is bad if it doesn't tell you what you need to know to fix it.
Starting with exactly which glyphs it had identified as failing

**Comment by eliheuer** [comment]
I looked at the `GDEF` table with `ttx` and the only class 2 glyphs are`f_i` and `f_l`, which have caret positions. So I will close this as I don't see what else I can do here.
