### ISSUE TITLE
Kerning Pairs

### ISSUE THREAD

**Issue by ecarras** [googlefonts/staatliches#17]
(V) (AE), Y (AE)

**Comment by eliheuer** [comment]
Great, thanks you! The pull request for your branch is here: https://github.com/googlefonts/staatliches/pull/18

It look like you need to sign a CLA before in can be merged. 

Thanks again!

**Comment by eliheuer** [comment]
Fixed with PR https://github.com/googlefonts/staatliches/pull/18
