### ISSUE TITLE
FontBakery Report -- Check 040: Failing

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/staatliches#6]
## Fontbakery report

<details>
<summary><b>[1] Staatliches-Regular.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 1006, but got 800 instead [code: ascent]
* :fire: **FAIL** OS/2.usWinDescent value should be equal or greater than 306, but got 200 instead [code: descent]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 0 | 0 | 0 | 0 |
| 0% | 100% | 0% | 0% | 0% | 0% |

**Comment by davelab6** [comment]
See Marc's gf-docs repo note on this

**Comment by eliheuer** [comment]
I'm never sure if I'm doing this correctly, will update the documentation if I ever figure it out. 

Here is what I'm going with to fix this issue -- (font-line output): 

```
 
=== fonts/Staatliches-Regular.ttf ===
Version 1.000; ttfautohint (v1.8)
SHA1: edebead881ba6d28beb4d32932b8e9736105cb85

--- Metrics ---
[head] Units per Em: 	1000
[head] yMax: 		1006
[head] yMin: 		-306
[OS/2] CapHeight: 	696
[OS/2] xHeight: 	500
[OS/2] TypoAscender: 	700
[OS/2] TypoDescender: 	-300
[OS/2] WinAscent: 	1006
[OS/2] WinDescent: 	306
[hhea] Ascent: 		700
[hhea] Descent: 	-300

[hhea] LineGap: 	250
[OS/2] TypoLineGap: 	250

--- Height Calculations by Table Values ---
[OS/2] TypoAscender to TypoDescender: 	1000
[OS/2] WinAscent to WinDescent: 	1312
[hhea] Ascent to Descent: 		1000

--- Delta Values ---
WinAscent to TypoAscender: 	306
Ascent to TypoAscender: 	0
WinDescent to TypoDescender: 	6
Descent to TypoDescender: 	0

--- Ratios ---
(Typo Asc + Desc + Linegap) / UPM: 	1.25
(winAsc + winDesc) / UPM: 		1.31
(hhea Asc + Desc) / UPM: 		1
```

**Comment by davelab6** [comment]
I believe you can trust font bakery on this; if it doesn't complain, you
are good to go
