### ISSUE TITLE
FontBakery Report -- Check has_ttfautohint_params: Failing

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/staatliches#8]
## Fontbakery report

<details>
<summary><b>[1] Staatliches-Regular.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Font has ttfautohint params? </summary>

* [com.google.fonts/check/has_ttfautohint_params](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/has_ttfautohint_params)
* :fire: **FAIL** Font is lacking ttfautohint params on its version strings on the name table.

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 0 | 0 | 0 | 0 |
| 0% | 100% | 0% | 0% | 0% | 0% |

**Comment by davelab6** [comment]
That shouldn't be fixed by ttx hacking, haha

It should be fixed by running ttfautohint with the correct args :))

**Comment by eliheuer** [comment]
Yes, of course, the missing `ttfautohint` arg was `-I`

**Comment by eliheuer** [comment]
PR https://github.com/googlefonts/staatliches/pull/22 fixes this
