### ISSUE TITLE
FontBakery Report -- Check 040 -- WARN

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/staatliches#9]
## Fontbakery report

<details>
<summary><b>[1] Staatliches-Regular.ttf</b></summary>
<details>
<summary>:warning: <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/065](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/065)
* :warning: **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 1 | 0 | 0 | 0 |
| 0% | 0% | 100% | 0% | 0% | 0% |

**Comment by eliheuer** [comment]
A good explanation of what this `WARN` is about can be found here: https://github.com/impallari/Raleway/issues/14

**Comment by eliheuer** [comment]
Looking at this font it might not need this. Feel free to reopen if I'm missing something.

**Comment by davelab6** [comment]
Can you add that note / link to the fb check itself please
